// <auto-generated />
using System;
using BackEndVirONet8.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndVirONet8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927074845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.Deporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Deportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fútbol"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Básquetbol"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tenis"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Natación"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Ciclismo"
                        });
                });

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.PersonaDeporte", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeporteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "DeporteId");

                    b.HasIndex("DeporteId");

                    b.ToTable("PersonaDeportes");
                });

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.PersonaDeporte", b =>
                {
                    b.HasOne("BackEndVirONet8.Domain.Entities.Deporte", "Deporte")
                        .WithMany("PersonaDeportes")
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndVirONet8.Domain.Entities.Persona", "Persona")
                        .WithMany("PersonaDeportes")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.Deporte", b =>
                {
                    b.Navigation("PersonaDeportes");
                });

            modelBuilder.Entity("BackEndVirONet8.Domain.Entities.Persona", b =>
                {
                    b.Navigation("PersonaDeportes");
                });
#pragma warning restore 612, 618
        }
    }
}
